---
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v